// Generated by https://quicktype.io

// JSON data datatypes
export interface PhotosData {
    photos: Photo[];
}

export interface Photo {
    _id: string;
    title: string;
    caption: string;
    source: string; 
    width: string;
    height: string;
    comments: Comment[];
}

export interface Comment {
    comment: string;
    author: string;
}
